Fix when collxml is missing fields req'd for major/minor rev-ing (#348)
Detecting text changes in a missing tag was not handled properly.

This implements the null object pattern and returns empty string for alltext().

Traceback:
  File "/var/cnx/apps/press/press/views/legacy_publishing.py", line 74, in publish
    db_conn)
  File "/var/cnx/apps/press/press/legacy_publishing/litezip.py", line 75, in publish_litezip
    modules_changed=modules_changed)
  File "/var/cnx/apps/press/press/legacy_publishing/collection.py", line 93, in publish_legacy_book
    elif needs_minor_rev(pre, post_tree):
  File "/var/cnx/apps/press/press/legacy_publishing/utils.py", line 54, in needs_minor_rev
    if pre.find('subjectlist').alltext() != post.find('subjectlist').alltext():
AttributeError: 'NoneType' object has no attribute 'alltext'